name: Bugfix Request
description: Criar uma solicitação de bugfix.
title: "[ANDROID][JIRA-ID] - Descrição curto do bugfix"
labels: ["bugfix"]
body:
  - type: markdown
    attributes:
      value: |
        "Preencha o formulário com sua solicitação de bugfix.
        A branch com a correção deverá apontar para a branch da release/x_x."
  - type: textarea
    id: description
    attributes:
      label: Descrição do bug
      description: Descreva aqui o problema
      placeholder: ex. app fecha quando clica no botão salvar
    validations:
      required: true
  - type: textarea
    id: cause
    attributes:
      label: Motivo do bug?
      description: Por que o bug não foi detectado durante a fase de validação? <br /> 
        Quais ações podem ser tomadas para evitar a solicitação desse bugfix?
    validations:
      required: true
  - type: textarea
    id: user_impact
    attributes:
      label: Impacto para o usuário
      description: Detalhe aqui o impacto na experiência do usuário causado por esse problema
      placeholder: ex. Ao navegar para a tela XPTO, ocorre um crash para o usuário.
    validations:
      required: true
  - type: textarea
    id: business_impact
    attributes:
      label: Risco para o negócio
      description: Informe o impacto para negócio que esse problema pode causar
      placeholder: ex. Dado o crash na tela XPTO, o usuário não consegue completar uma transação financeira.
    validations:
      required: true
  - type: input
    id: retest_team
    attributes:
      label: ReTest
      description: Liste os times que precisam validar a correção do problema
      placeholder: ex. Odin, Kattegat
    validations:
      required: true
